In [1]:
import numpy as np
import time

In [5]:
# execution performance
# List VS numpy arrays

size=10_000_000
#python list
py_list=list(range(size))
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time={end-start} seconds")

#numpy arrays
np_array=np.array(py_list)
start=time.time()
sq_array=np_array ** 2
end=time.time()
print(f"numpy array time={end-start} seconds")


python list time=8.096473455429077 seconds
numpy array time=0.18784403800964355 seconds


In [8]:
#memory
import sys
print(f"python list size={sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size={np_array.nbytes} bytes")

python list size=800000560000000 bytes
numpy array size=80000000 bytes


In [10]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2d,arr2d.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [13]:
iden=np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#properties of array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #mxn
print(arr.size) #total size
print(arr.dtype) #integer values
print(arr.ndim) #no of dimensions

(3, 3)
9
int64
2


In [23]:
#operations on array
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flat=arr.flatten() #2D->1D
print(flat,flat.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [14]:
# Normal indexing

# 1d indexing
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[4])

# 2d indexing
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0][1])

#fancy indexing
idx=[0,1,3]
print(arr[idx])
# print(arr2[idx])



1
5
2
[1 2 4]


In [20]:
#slicing
arr=np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[1::2])


[2 3 4]
[1 2 3 4]
[2 3 4 5]
[2 4]


In [26]:
#copy vs view
# python list creates a copy of an array/list 
# while np array creates a view of an array


# list

# nums=[1,2,3,4,5]
# sub_list=nums[1:3]
# print(sub_list)
# sub_list[0]=200
# print(sub_list)
# print(nums)

# np array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3].copy()
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)
#this is a like a reference pointer but to actually make a copy we can use ".copy" function

[2 3]
[200   3]
[1 2 3 4 5]


In [8]:
arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)
arr2=np.array([1,2,3.14,4,5])
print(arr2,arr2.dtype)


# complex numbers
arr1=np.array([3+5j])
arr3=np.array([2+3j])
print(arr1+arr3)
print(arr1-arr3)


[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
[5.+8.j]
[1.+2.j]


In [13]:
#Multi-dimensional array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

#sum of all columns
sum_of_col=np.sum(arr2D,axis=0)
# print(sum_of_col)

#sum of all rows
sum_of_rows=np.sum(arr2D,axis=1)
# print(sum_of_rows)

print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [20]:
#3D array
arr3d=np.array( [ [[1,2],[3,4],[5,6]] , [[7,8],[9,10],[11,12]] , [[13,14],[15,16],[17,18]]] ) #2x3x2
print(arr3d,arr3d.shape)

print(arr3d[1,1,0])
#slicing
print(arr3d[:,0,:]) #first row from both layers


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]] (3, 3, 2)
9
[[ 1  2]
 [ 7  8]
 [13 14]]


In [22]:
# Vectorization
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr1+arr2)

# broadcasting=scaling your np arrays without using extra space

[ 7  9 11 13 15]


In [25]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr1 + arr2)



(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [7]:
#normalization
arr2=np.array([[1,2],[3,4]])

mean=np.mean(arr2)
std_dev=np.std(arr2)

norm_arr=(arr2-mean)/std_dev
print(norm_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [9]:
#mathematical function
arr=np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [14]:
arr=np.array([1,2,3,4,5])

#power function
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

# log function
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [22]:
#rounding function

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.94))
print(np.trunc(3.94))

arr=np.array([1,2,4,3,4,5,5,8,8]) 

print(np.unique(arr))# prints unique values like a set
print(np.sort(arr))#sorts the array
print(np.abs(arr))#makes neg values positive


3.0
4.0
3.0
3.0
[1 2 3 4 5 8]
[1 2 3 4 4 5 5 8 8]
